manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/ReFil
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: rgb-battery-effect
      import: app/west.yml
  self:
    path: config
