manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/ReFil
  projects:
    - name: zmk
      remote: ReFil
      revision: funkylights
      import: app/west.yml
  self:
    path: config
