manifest:
  remotes:
    - name: zmk_yyz
      url-base: https://github.com/dywj
  projects:
    - name: zmk_yyz
      remote: zmk_yyz
      revision: main
      import: app/west.yml
  self:
    path: config
